// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type BehaviorOnMXFailure string

const (
	BehaviorOnMXFailure_RejectMessage   BehaviorOnMXFailure = "RejectMessage"
	BehaviorOnMXFailure_UseDefaultValue BehaviorOnMXFailure = "UseDefaultValue"
)

type BounceType string

const (
	BounceType_ContentRejected  BounceType = "ContentRejected"
	BounceType_DoesNotExist     BounceType = "DoesNotExist"
	BounceType_ExceededQuota    BounceType = "ExceededQuota"
	BounceType_MessageTooLarge  BounceType = "MessageTooLarge"
	BounceType_TemporaryFailure BounceType = "TemporaryFailure"
	BounceType_Undefined        BounceType = "Undefined"
)

type BulkEmailStatus string

const (
	BulkEmailStatus_AccountDailyQuotaExceeded     BulkEmailStatus = "AccountDailyQuotaExceeded"
	BulkEmailStatus_AccountSendingPaused          BulkEmailStatus = "AccountSendingPaused"
	BulkEmailStatus_AccountSuspended              BulkEmailStatus = "AccountSuspended"
	BulkEmailStatus_AccountThrottled              BulkEmailStatus = "AccountThrottled"
	BulkEmailStatus_ConfigurationSetDoesNotExist  BulkEmailStatus = "ConfigurationSetDoesNotExist"
	BulkEmailStatus_ConfigurationSetSendingPaused BulkEmailStatus = "ConfigurationSetSendingPaused"
	BulkEmailStatus_Failed                        BulkEmailStatus = "Failed"
	BulkEmailStatus_InvalidParameterValue         BulkEmailStatus = "InvalidParameterValue"
	BulkEmailStatus_InvalidSendingPoolName        BulkEmailStatus = "InvalidSendingPoolName"
	BulkEmailStatus_MailFromDomainNotVerified     BulkEmailStatus = "MailFromDomainNotVerified"
	BulkEmailStatus_MessageRejected               BulkEmailStatus = "MessageRejected"
	BulkEmailStatus_Success                       BulkEmailStatus = "Success"
	BulkEmailStatus_TemplateDoesNotExist          BulkEmailStatus = "TemplateDoesNotExist"
	BulkEmailStatus_TransientFailure              BulkEmailStatus = "TransientFailure"
)

type ConfigurationSetAttribute string

const (
	ConfigurationSetAttribute_deliveryOptions   ConfigurationSetAttribute = "deliveryOptions"
	ConfigurationSetAttribute_eventDestinations ConfigurationSetAttribute = "eventDestinations"
	ConfigurationSetAttribute_reputationOptions ConfigurationSetAttribute = "reputationOptions"
	ConfigurationSetAttribute_trackingOptions   ConfigurationSetAttribute = "trackingOptions"
)

type CustomMailFromStatus string

const (
	CustomMailFromStatus_Failed           CustomMailFromStatus = "Failed"
	CustomMailFromStatus_Pending          CustomMailFromStatus = "Pending"
	CustomMailFromStatus_Success          CustomMailFromStatus = "Success"
	CustomMailFromStatus_TemporaryFailure CustomMailFromStatus = "TemporaryFailure"
)

type DimensionValueSource string

const (
	DimensionValueSource_emailHeader DimensionValueSource = "emailHeader"
	DimensionValueSource_linkTag     DimensionValueSource = "linkTag"
	DimensionValueSource_messageTag  DimensionValueSource = "messageTag"
)

type DsnAction string

const (
	DsnAction_delayed   DsnAction = "delayed"
	DsnAction_delivered DsnAction = "delivered"
	DsnAction_expanded  DsnAction = "expanded"
	DsnAction_failed    DsnAction = "failed"
	DsnAction_relayed   DsnAction = "relayed"
)

type EventType string

const (
	EventType_bounce           EventType = "bounce"
	EventType_click            EventType = "click"
	EventType_complaint        EventType = "complaint"
	EventType_delivery         EventType = "delivery"
	EventType_open             EventType = "open"
	EventType_reject           EventType = "reject"
	EventType_renderingFailure EventType = "renderingFailure"
	EventType_send             EventType = "send"
)

type IdentityType string

const (
	IdentityType_Domain       IdentityType = "Domain"
	IdentityType_EmailAddress IdentityType = "EmailAddress"
)

type InvocationType string

const (
	InvocationType_Event           InvocationType = "Event"
	InvocationType_RequestResponse InvocationType = "RequestResponse"
)

type NotificationType string

const (
	NotificationType_Bounce    NotificationType = "Bounce"
	NotificationType_Complaint NotificationType = "Complaint"
	NotificationType_Delivery  NotificationType = "Delivery"
)

type ReceiptFilterPolicy string

const (
	ReceiptFilterPolicy_Allow ReceiptFilterPolicy = "Allow"
	ReceiptFilterPolicy_Block ReceiptFilterPolicy = "Block"
)

type SNSActionEncoding string

const (
	SNSActionEncoding_Base64 SNSActionEncoding = "Base64"
	SNSActionEncoding_UTF_8  SNSActionEncoding = "UTF-8"
)

type StopScope string

const (
	StopScope_RuleSet StopScope = "RuleSet"
)

type TLSPolicy string

const (
	TLSPolicy_Optional TLSPolicy = "Optional"
	TLSPolicy_Require  TLSPolicy = "Require"
)

type VerificationStatus string

const (
	VerificationStatus_Failed           VerificationStatus = "Failed"
	VerificationStatus_NotStarted       VerificationStatus = "NotStarted"
	VerificationStatus_Pending          VerificationStatus = "Pending"
	VerificationStatus_Success          VerificationStatus = "Success"
	VerificationStatus_TemporaryFailure VerificationStatus = "TemporaryFailure"
)
