//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BounceAction) DeepCopyInto(out *BounceAction) {
	*out = *in
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BounceAction.
func (in *BounceAction) DeepCopy() *BounceAction {
	if in == nil {
		return nil
	}
	out := new(BounceAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BouncedRecipientInfo) DeepCopyInto(out *BouncedRecipientInfo) {
	*out = *in
	if in.RecipientARN != nil {
		in, out := &in.RecipientARN, &out.RecipientARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BouncedRecipientInfo.
func (in *BouncedRecipientInfo) DeepCopy() *BouncedRecipientInfo {
	if in == nil {
		return nil
	}
	out := new(BouncedRecipientInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudWatchDestination) DeepCopyInto(out *CloudWatchDestination) {
	*out = *in
	if in.DimensionConfigurations != nil {
		in, out := &in.DimensionConfigurations, &out.DimensionConfigurations
		*out = make([]*CloudWatchDimensionConfiguration, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CloudWatchDimensionConfiguration)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudWatchDestination.
func (in *CloudWatchDestination) DeepCopy() *CloudWatchDestination {
	if in == nil {
		return nil
	}
	out := new(CloudWatchDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudWatchDimensionConfiguration) DeepCopyInto(out *CloudWatchDimensionConfiguration) {
	*out = *in
	if in.DefaultDimensionValue != nil {
		in, out := &in.DefaultDimensionValue, &out.DefaultDimensionValue
		*out = new(string)
		**out = **in
	}
	if in.DimensionName != nil {
		in, out := &in.DimensionName, &out.DimensionName
		*out = new(string)
		**out = **in
	}
	if in.DimensionValueSource != nil {
		in, out := &in.DimensionValueSource, &out.DimensionValueSource
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudWatchDimensionConfiguration.
func (in *CloudWatchDimensionConfiguration) DeepCopy() *CloudWatchDimensionConfiguration {
	if in == nil {
		return nil
	}
	out := new(CloudWatchDimensionConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSet) DeepCopyInto(out *ConfigurationSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSet.
func (in *ConfigurationSet) DeepCopy() *ConfigurationSet {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigurationSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSetList) DeepCopyInto(out *ConfigurationSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigurationSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSetList.
func (in *ConfigurationSetList) DeepCopy() *ConfigurationSetList {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigurationSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSetSpec) DeepCopyInto(out *ConfigurationSetSpec) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSetSpec.
func (in *ConfigurationSetSpec) DeepCopy() *ConfigurationSetSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSetStatus) DeepCopyInto(out *ConfigurationSetStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSetStatus.
func (in *ConfigurationSetStatus) DeepCopy() *ConfigurationSetStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSet_SDK) DeepCopyInto(out *ConfigurationSet_SDK) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSet_SDK.
func (in *ConfigurationSet_SDK) DeepCopy() *ConfigurationSet_SDK {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSet_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeliveryOptions) DeepCopyInto(out *DeliveryOptions) {
	*out = *in
	if in.TLSPolicy != nil {
		in, out := &in.TLSPolicy, &out.TLSPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeliveryOptions.
func (in *DeliveryOptions) DeepCopy() *DeliveryOptions {
	if in == nil {
		return nil
	}
	out := new(DeliveryOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventDestination) DeepCopyInto(out *EventDestination) {
	*out = *in
	if in.CloudWatchDestination != nil {
		in, out := &in.CloudWatchDestination, &out.CloudWatchDestination
		*out = new(CloudWatchDestination)
		(*in).DeepCopyInto(*out)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.KinesisFirehoseDestination != nil {
		in, out := &in.KinesisFirehoseDestination, &out.KinesisFirehoseDestination
		*out = new(KinesisFirehoseDestination)
		(*in).DeepCopyInto(*out)
	}
	if in.MatchingEventTypes != nil {
		in, out := &in.MatchingEventTypes, &out.MatchingEventTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SNSDestination != nil {
		in, out := &in.SNSDestination, &out.SNSDestination
		*out = new(SNSDestination)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventDestination.
func (in *EventDestination) DeepCopy() *EventDestination {
	if in == nil {
		return nil
	}
	out := new(EventDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityDkimAttributes) DeepCopyInto(out *IdentityDkimAttributes) {
	*out = *in
	if in.DkimEnabled != nil {
		in, out := &in.DkimEnabled, &out.DkimEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityDkimAttributes.
func (in *IdentityDkimAttributes) DeepCopy() *IdentityDkimAttributes {
	if in == nil {
		return nil
	}
	out := new(IdentityDkimAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityNotificationAttributes) DeepCopyInto(out *IdentityNotificationAttributes) {
	*out = *in
	if in.ForwardingEnabled != nil {
		in, out := &in.ForwardingEnabled, &out.ForwardingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.HeadersInBounceNotificationsEnabled != nil {
		in, out := &in.HeadersInBounceNotificationsEnabled, &out.HeadersInBounceNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.HeadersInComplaintNotificationsEnabled != nil {
		in, out := &in.HeadersInComplaintNotificationsEnabled, &out.HeadersInComplaintNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.HeadersInDeliveryNotificationsEnabled != nil {
		in, out := &in.HeadersInDeliveryNotificationsEnabled, &out.HeadersInDeliveryNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityNotificationAttributes.
func (in *IdentityNotificationAttributes) DeepCopy() *IdentityNotificationAttributes {
	if in == nil {
		return nil
	}
	out := new(IdentityNotificationAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KinesisFirehoseDestination) DeepCopyInto(out *KinesisFirehoseDestination) {
	*out = *in
	if in.DeliveryStreamARN != nil {
		in, out := &in.DeliveryStreamARN, &out.DeliveryStreamARN
		*out = new(string)
		**out = **in
	}
	if in.IAMRoleARN != nil {
		in, out := &in.IAMRoleARN, &out.IAMRoleARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KinesisFirehoseDestination.
func (in *KinesisFirehoseDestination) DeepCopy() *KinesisFirehoseDestination {
	if in == nil {
		return nil
	}
	out := new(KinesisFirehoseDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LambdaAction) DeepCopyInto(out *LambdaAction) {
	*out = *in
	if in.FunctionARN != nil {
		in, out := &in.FunctionARN, &out.FunctionARN
		*out = new(string)
		**out = **in
	}
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LambdaAction.
func (in *LambdaAction) DeepCopy() *LambdaAction {
	if in == nil {
		return nil
	}
	out := new(LambdaAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptRule) DeepCopyInto(out *ReceiptRule) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ScanEnabled != nil {
		in, out := &in.ScanEnabled, &out.ScanEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TLSPolicy != nil {
		in, out := &in.TLSPolicy, &out.TLSPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptRule.
func (in *ReceiptRule) DeepCopy() *ReceiptRule {
	if in == nil {
		return nil
	}
	out := new(ReceiptRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReputationOptions) DeepCopyInto(out *ReputationOptions) {
	*out = *in
	if in.LastFreshStart != nil {
		in, out := &in.LastFreshStart, &out.LastFreshStart
		*out = (*in).DeepCopy()
	}
	if in.ReputationMetricsEnabled != nil {
		in, out := &in.ReputationMetricsEnabled, &out.ReputationMetricsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SendingEnabled != nil {
		in, out := &in.SendingEnabled, &out.SendingEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReputationOptions.
func (in *ReputationOptions) DeepCopy() *ReputationOptions {
	if in == nil {
		return nil
	}
	out := new(ReputationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Action) DeepCopyInto(out *S3Action) {
	*out = *in
	if in.KMSKeyARN != nil {
		in, out := &in.KMSKeyARN, &out.KMSKeyARN
		*out = new(string)
		**out = **in
	}
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Action.
func (in *S3Action) DeepCopy() *S3Action {
	if in == nil {
		return nil
	}
	out := new(S3Action)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SNSAction) DeepCopyInto(out *SNSAction) {
	*out = *in
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SNSAction.
func (in *SNSAction) DeepCopy() *SNSAction {
	if in == nil {
		return nil
	}
	out := new(SNSAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SNSDestination) DeepCopyInto(out *SNSDestination) {
	*out = *in
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SNSDestination.
func (in *SNSDestination) DeepCopy() *SNSDestination {
	if in == nil {
		return nil
	}
	out := new(SNSDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StopAction) DeepCopyInto(out *StopAction) {
	*out = *in
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StopAction.
func (in *StopAction) DeepCopy() *StopAction {
	if in == nil {
		return nil
	}
	out := new(StopAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackingOptions) DeepCopyInto(out *TrackingOptions) {
	*out = *in
	if in.CustomRedirectDomain != nil {
		in, out := &in.CustomRedirectDomain, &out.CustomRedirectDomain
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackingOptions.
func (in *TrackingOptions) DeepCopy() *TrackingOptions {
	if in == nil {
		return nil
	}
	out := new(TrackingOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkmailAction) DeepCopyInto(out *WorkmailAction) {
	*out = *in
	if in.OrganizationARN != nil {
		in, out := &in.OrganizationARN, &out.OrganizationARN
		*out = new(string)
		**out = **in
	}
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkmailAction.
func (in *WorkmailAction) DeepCopy() *WorkmailAction {
	if in == nil {
		return nil
	}
	out := new(WorkmailAction)
	in.DeepCopyInto(out)
	return out
}
